# Docker-compose.yml
version: "3.8"
services:
   nginx:
    build: 
      context: .  # Đường dẫn tới thư mục chứa Dockerfile của nginx
    ports:
      - '3000:3000'  # Expose cổng 3000 trên máy chủ, chuyển tiếp tới cổng 80 của Nginx
    volumes:
      - ../../client/build:/usr/share/nginx/html  # Gắn thư mục build của frontend vào Nginx
      - ./default.conf:/etc/nginx/conf.d/default.conf  