version: "3.8"

services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    env_file:
      - ../api/.env
    container_name: api
    ports:
      - "8800:8800"
    volumes:
      - ../api:/src/api
    restart: always

  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000" # Serve React app trên cổng 3000
    volumes:
      - ../client:/src/client
    restart: always
